/*
  PetLink Master Database Schema
  Combined & Improved Version
  
  Includes features for:
  - User Profiles (Citizens, Rescuers, Shelters, Vets) with Location Mapping
  - Notify Rescuer (Reports) with Assignment & Geolocation
  - Adoption Center 2.0 (Detailed Pet Profiles & Adoption Requests)
  - Book Appointments (Veterinary Scheduling)
  - Wishlist

  WARNING: Running this script will DROP all existing tables and data.
*/

-- -----------------------------------------------------------------------------
-- 0. CLEANUP
-- -----------------------------------------------------------------------------
-- Drop tables in reverse dependency order to avoid constraint errors
DROP TABLE IF EXISTS public.appointments CASCADE;
DROP TABLE IF EXISTS public.wishlist CASCADE;
DROP TABLE IF EXISTS public.adoption_requests CASCADE;
DROP TABLE IF EXISTS public.adoptions CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.reports CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- -----------------------------------------------------------------------------
-- 1. PROFILES
-- Central user table for all roles.
-- -----------------------------------------------------------------------------
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  
  -- Role Management
  role text check (role in ('user', 'rescuer', 'shelter', 'vet')) default 'user',
  
  -- Profile Info
  full_name text,
  about text,
  goal text, -- For Organizations
  avatar_url text,
  
  -- Location (Crucial for Maps feature)
  location text, -- City/Area name (e.g. "Colombo 07")
  address text,  -- Full street address
  latitude float,  -- Precise mapping
  longitude float, -- Precise mapping

  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Profiles Security
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone" 
  on public.profiles for select using (true);

create policy "Users can insert their own profile" 
  on public.profiles for insert with check (auth.uid() = id);

create policy "Users can update their own profile" 
  on public.profiles for update using (auth.uid() = id);


-- -----------------------------------------------------------------------------
-- 2. REPORTS (Notify Rescuer)
-- Rescue requests submitted by Citizens.
-- -----------------------------------------------------------------------------
create table public.reports (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null, -- Citizen
  
  -- Report Details
  description text not null,
  urgency text check (urgency in ('low', 'medium', 'high', 'critical')),
  image_url text,
  
  -- Location
  location text, -- text description
  latitude float,
  longitude float,

  -- Management
  assigned_rescuer_id uuid references public.profiles(id), -- Specific NGO notified
  status text default 'pending' check (status in ('pending', 'accepted', 'resolved', 'rejected')),
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Reports Security
alter table public.reports enable row level security;

create policy "Reports are viewable by everyone" 
  on public.reports for select using (true);

create policy "Citizens can create reports" 
  on public.reports for insert with check (auth.role() = 'authenticated');

create policy "Users can update their own reports" 
  on public.reports for update using (auth.uid() = user_id);

create policy "Rescuers can update assigned reports" 
  on public.reports for update using (auth.uid() = assigned_rescuer_id);


-- -----------------------------------------------------------------------------
-- 3. ADOPTIONS (Adoption Center 2.0)
-- Detailed pet listings.
-- -----------------------------------------------------------------------------
create table public.adoptions (
  id bigint generated by default as identity primary key,
  contact_info text,
  posted_by uuid references public.profiles(id) not null, -- Posted by (NGO)
  
  -- Pet Basic Info
  name text not null,
  species text not null, -- Dog, Cat, etc.
  breed text,
  age_years int,
  age_months int,
  gender text check (gender in ('Male', 'Female', 'Unknown')),
  description text,
  image_url text,
  
  -- Medical & Behavior (2.0 Features)
  medical_history text,
  vaccinated boolean default false,
  neutered boolean default false,
  behavior_notes text,
  good_with_kids boolean default null,
  good_with_pets boolean default null,
  
  -- Status
  status text default 'available' check (status in ('available', 'pending', 'adopted')),
  location text, -- City/Area
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Adoptions Security
alter table public.adoptions enable row level security;

create policy "Adoptions are viewable by everyone" 
  on public.adoptions for select using (true);

create policy "NGOs can create listings" 
  on public.adoptions for insert with check (
    exists ( select 1 from public.profiles where profiles.id = auth.uid() and profiles.role in ('rescuer', 'shelter', 'vet') )
  );

create policy "Owners can update their listings" 
  on public.adoptions for update using (auth.uid() = posted_by);


-- -----------------------------------------------------------------------------
-- 4. ADOPTION REQUESTS
-- Applications sent by users for a pet.
-- -----------------------------------------------------------------------------
create table public.adoption_requests (
  id bigint generated by default as identity primary key,
  adoption_id bigint references public.adoptions(id) on delete cascade not null,
  requester_id uuid references public.profiles(id) not null,
  
  -- Application Info
  message text,
  phone text,
  address text,
  living_situation text,
  experience text,
  has_other_pets boolean default false,
  
  status text default 'pending' check (status in ('pending', 'under_review', 'approved', 'rejected')),
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Adoption Requests Security
alter table public.adoption_requests enable row level security;

create policy "Users can view their own requests" 
  on public.adoption_requests for select using (auth.uid() = requester_id);

create policy "Owners (NGOs) can view requests for their pets" 
  on public.adoption_requests for select using (
    exists ( select 1 from public.adoptions where adoptions.id = adoption_requests.adoption_id and adoptions.posted_by = auth.uid() )
  );

create policy "Users can create requests" 
  on public.adoption_requests for insert with check (auth.role() = 'authenticated');

create policy "Owners and Requesters can update status" 
  on public.adoption_requests for update using (
    auth.uid() = requester_id OR 
    exists ( select 1 from public.adoptions where adoptions.id = adoption_requests.adoption_id and adoptions.posted_by = auth.uid() )
  );


-- -----------------------------------------------------------------------------
-- 5. WISHLIST
-- -----------------------------------------------------------------------------
create table public.wishlist (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  adoption_id bigint references public.adoptions(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, adoption_id)
);

alter table public.wishlist enable row level security;

create policy "Users can view/manage own wishlist" 
  on public.wishlist for all using (auth.uid() = user_id);


-- -----------------------------------------------------------------------------
-- 6. APPOINTMENTS (Veterinary Bookings)
-- -----------------------------------------------------------------------------
create table public.appointments (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null, -- Pet Owner
  vet_id uuid references public.profiles(id) not null, -- Vet Profile
  
  service_type text, -- sterilization, vaccination
  date date not null,
  time_slot text not null,
  
  status text default 'pending' check (status in ('pending', 'upcoming', 'completed', 'cancelled', 'rejected')),
  notes text,

  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.appointments enable row level security;

create policy "Users can view their own appointments" 
  on public.appointments for select using (auth.uid() = user_id);

create policy "Vets can view appointments assigned to them" 
  on public.appointments for select using (auth.uid() = vet_id);

create policy "Users can create appointments" 
  on public.appointments for insert with check (auth.uid() = user_id);

create policy "Participants can update appointments" 
  on public.appointments for update using (auth.uid() = user_id or auth.uid() = vet_id);


-- -----------------------------------------------------------------------------
-- 7. NOTIFICATIONS
-- Real-time alerts for users.
-- -----------------------------------------------------------------------------
create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null, -- Recipient
  type text check (type in ('appointment_request', 'status_change', 'adoption_request', 'details')),
  message text not null,
  is_read boolean default false,
  metadata jsonb, -- Store related IDs e.g. { "appointment_id": 123 }
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.notifications enable row level security;

create policy "Users can view their own notifications" 
  on public.notifications for select using (auth.uid() = user_id);

create policy "Users can update their own notifications" 
  on public.notifications for update using (auth.uid() = user_id);

create policy "System and Users can insert notifications" 
  on public.notifications for insert with check (auth.role() = 'authenticated');


-- -----------------------------------------------------------------------------
-- STORAGE BUCKET CONFIGURATION (Instructions)
-- -----------------------------------------------------------------------------
/*
  IMPORTANT: You must manually enable these buckets in the Supabase Dashboard -> Storage.
  1. 'avatars' (Public)
  2. 'rescue-images' (Public)
  3. 'adoption-images' (Public)
  
  The policies below ensure security if these buckets exist.
*/

-- (Optional) SQL to set up storage policies if buckets exist
-- create policy "Public Access Avatars" on storage.objects for select using ( bucket_id = 'avatars' );
-- create policy "Authenticated Upload Avatars" on storage.objects for insert with check ( bucket_id = 'avatars' and auth.role() = 'authenticated' );

-- create policy "Public Access Rescue" on storage.objects for select using ( bucket_id = 'rescue-images' );
-- create policy "Authenticated Upload Rescue" on storage.objects for insert with check ( bucket_id = 'rescue-images' and auth.role() = 'authenticated' );

-- create policy "Public Access Adoption" on storage.objects for select using ( bucket_id = 'adoption-images' );
-- create policy "Authenticated Upload Adoption" on storage.objects for insert with check ( bucket_id = 'adoption-images' and auth.role() = 'authenticated' );
